defaults: &defaults
  site:
    name: EngineerBlogs.Map!
    title: 技術ブログ共有サイト
    description: 技術ブログの共有サイトです。自分に合ったブログを見つけて効率的にインプットしましょう！またおすすめのブログや、ご自身のブログがあればぜひ紹介して下さい！
    meta:
      ogp:
        app_id: Facebook App ID
        type: article
        image_path: /app/assets/images/twitter_card.png

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults